"""Architectural and Enterprise design patterns."""

from design_patterns.architectural.dependency_injection import (
    ConsoleNotificationService,
    Container,
    MockPaymentGateway,
    NotificationService,
    OrderCheckoutService,
    PaymentGateway,
    Scope,
    StandardTaxCalculator,
    StripePaymentGateway,
    TaxCalculator,
)
from design_patterns.architectural.event_pubsub import (
    EmailNotificationListener,
    Event,
    EventBus,
    InventoryReservationListener,
    OrderPlacedEvent,
    PaymentReceivedEvent,
    ShipmentDispatchedEvent,
)
from design_patterns.architectural.registry import (
    DocumentExporter,
    HTMLExporter,
    JSONExporter,
    MarkdownExporter,
    PluginRegistry,
    exporter_registry,
)
from design_patterns.architectural.repository import (
    InMemoryUserRepository,
    Repository,
    User,
    UserService,
)
from design_patterns.architectural.specification import (
    AndSpecification,
    CategorySpecification,
    InStockSpecification,
    MinimumRatingSpecification,
    NotSpecification,
    OrSpecification,
    PriceBetweenSpecification,
    Product,
    Specification,
    filter_by_specification,
)
from design_patterns.architectural.unit_of_work import (
    AbstractUnitOfWork,
    Account,
    BankTransferService,
    InMemoryUnitOfWork,
)

__all__ = [
    "AbstractUnitOfWork",
    "Account",
    "AndSpecification",
    "BankTransferService",
    "CategorySpecification",
    "ConsoleNotificationService",
    "Container",
    "DocumentExporter",
    "EmailNotificationListener",
    "Event",
    "EventBus",
    "HTMLExporter",
    "InMemoryUnitOfWork",
    "InMemoryUserRepository",
    "InStockSpecification",
    "InventoryReservationListener",
    "JSONExporter",
    "MarkdownExporter",
    "MinimumRatingSpecification",
    "MockPaymentGateway",
    "NotSpecification",
    "NotificationService",
    "OrSpecification",
    "OrderCheckoutService",
    "OrderPlacedEvent",
    "PaymentGateway",
    "PaymentReceivedEvent",
    "PluginRegistry",
    "PriceBetweenSpecification",
    "Product",
    "Repository",
    "Scope",
    "ShipmentDispatchedEvent",
    "Specification",
    "StandardTaxCalculator",
    "StripePaymentGateway",
    "TaxCalculator",
    "User",
    "UserService",
    "exporter_registry",
    "filter_by_specification",
]
