"""Builder Design Pattern.

Classification: Creational
Intent:
    Separate the construction of a complex object from its representation so that
    the same construction process can create different representations.

Motivation & Real-World Analogy:
    Constructing complex domain objects (such as an HTTP Request or a SQL Query)
    frequently suffers from the "telescoping constructor" anti-pattern, where
    constructors take dozens of parameters—many optional or dependent on one another.
    A Builder provides a readable, fluent, step-by-step construction pipeline that
    validates constraints before returning an immutable product.

Mermaid Architecture Diagram:
    ```mermaid
    classDiagram
        class HttpRequest {
            +method: str
            +url: str
            +headers: dict
            +params: dict
            +body: bytes | None
            +timeout: float
        }
        class HttpRequestBuilder {
            <<protocol>>
            +set_url(url: str) Self
            +set_method(method: str) Self
            +add_header(key: str, value: str) Self
            +set_body(body: bytes) Self
            +build() HttpRequest
        }
        class ConcreteHttpRequestBuilder {
            -url: str
            -method: str
            -headers: dict
            +build() HttpRequest
        }
        class RequestDirector {
            -builder: HttpRequestBuilder
            +make_json_get(url: str) HttpRequest
            +make_json_post(url: str, payload: bytes) HttpRequest
        }
        HttpRequestBuilder <|.. ConcreteHttpRequestBuilder
        ConcreteHttpRequestBuilder ..> HttpRequest : constructs
        RequestDirector o--> HttpRequestBuilder
    ```
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any, Protocol, Self


# ==============================================================================
# 1. Anti-Pattern / Naive Approach (Telescoping Constructor)
# ==============================================================================
class NaiveHttpRequest:
    """Anti-pattern: Telescoping constructor with mutable defaults and parameter soup."""

    def __init__(
        self,
        url: str,
        method: str = "GET",
        headers: dict[str, str] | None = None,
        params: dict[str, str] | None = None,
        body: bytes | None = None,
        timeout: float = 30.0,
        verify_ssl: bool = True,
        max_retries: int = 3,
        auth_token: str | None = None,
    ) -> None:
        self.url = url
        self.method = method
        self.headers = headers if headers is not None else {}
        self.params = params if params is not None else {}
        self.body = body
        self.timeout = timeout
        self.verify_ssl = verify_ssl
        self.max_retries = max_retries
        self.auth_token = auth_token


# ==============================================================================
# 2. Clean Pattern Implementation (GoF Builder with Fluent Interface)
# ==============================================================================
@dataclass(frozen=True)
class HttpRequest:
    """Immutable Product generated by the Builder."""

    url: str
    method: str
    headers: dict[str, str] = field(default_factory=dict)
    params: dict[str, str] = field(default_factory=dict)
    body: bytes | None = None
    timeout: float = 30.0
    verify_ssl: bool = True
    max_retries: int = 3


class HttpRequestBuilder(Protocol):
    """Builder Interface: Defines steps to construct the HttpRequest."""

    def reset(self) -> Self: ...
    def set_url(self, url: str) -> Self: ...
    def set_method(self, method: str) -> Self: ...
    def add_header(self, key: str, value: str) -> Self: ...
    def add_param(self, key: str, value: str) -> Self: ...
    def set_body(self, body: bytes | None) -> Self: ...
    def set_timeout(self, timeout: float) -> Self: ...
    def set_verify_ssl(self, verify: bool) -> Self: ...
    def set_max_retries(self, retries: int) -> Self: ...
    def build(self) -> HttpRequest: ...


class ConcreteHttpRequestBuilder:
    """Concrete Builder implementing step-by-step assembly with validation."""

    def __init__(self) -> None:
        self.reset()

    def reset(self) -> Self:
        self._url: str | None = None
        self._method: str = "GET"
        self._headers: dict[str, str] = {}
        self._params: dict[str, str] = {}
        self._body: bytes | None = None
        self._timeout: float = 30.0
        self._verify_ssl: bool = True
        self._max_retries: int = 3
        return self

    def set_url(self, url: str) -> Self:
        if not (url.startswith("http://") or url.startswith("https://")):
            raise ValueError(f"URL must start with http:// or https://: {url}")
        self._url = url
        return self

    def set_method(self, method: str) -> Self:
        valid_methods = {"GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS"}
        upper = method.upper()
        if upper not in valid_methods:
            raise ValueError(f"Invalid HTTP method: {method}")
        self._method = upper
        return self

    def add_header(self, key: str, value: str) -> Self:
        self._headers[key] = value
        return self

    def add_param(self, key: str, value: str) -> Self:
        self._params[key] = value
        return self

    def set_body(self, body: bytes | None) -> Self:
        self._body = body
        return self

    def set_timeout(self, timeout: float) -> Self:
        if timeout <= 0:
            raise ValueError("Timeout must be strictly positive")
        self._timeout = timeout
        return self

    def set_verify_ssl(self, verify: bool) -> Self:
        self._verify_ssl = verify
        return self

    def set_max_retries(self, retries: int) -> Self:
        if retries < 0:
            raise ValueError("Max retries cannot be negative")
        self._max_retries = retries
        return self

    def build(self) -> HttpRequest:
        """Validates internal invariants and constructs the final immutable product."""
        if not self._url:
            raise ValueError("Cannot build HttpRequest without a valid URL")

        # Invariant check: GET / HEAD should not typically have a body
        if self._method in {"GET", "HEAD"} and self._body is not None:
            raise ValueError(f"HTTP {self._method} requests cannot contain a request body")

        product = HttpRequest(
            url=self._url,
            method=self._method,
            headers=dict(self._headers),
            params=dict(self._params),
            body=self._body,
            timeout=self._timeout,
            verify_ssl=self._verify_ssl,
            max_retries=self._max_retries,
        )
        self.reset()
        return product


class RequestDirector:
    """Director: Enforces standard recipes for commonly used complex configurations."""

    def __init__(self, builder: ConcreteHttpRequestBuilder) -> None:
        self._builder = builder

    def construct_json_get(self, url: str) -> HttpRequest:
        return (
            self._builder.reset()
            .set_url(url)
            .set_method("GET")
            .add_header("Accept", "application/json")
            .build()
        )

    def construct_json_post(self, url: str, payload: dict[str, Any]) -> HttpRequest:
        encoded = json.dumps(payload).encode("utf-8")
        return (
            self._builder.reset()
            .set_url(url)
            .set_method("POST")
            .add_header("Content-Type", "application/json")
            .add_header("Accept", "application/json")
            .set_body(encoded)
            .build()
        )


# ==============================================================================
# 3. Pythonic Twist: Fluent Query / Payload Builder with Dunder Context or Kwargs
# ==============================================================================
class PythonicRequestBuilder:
    """Lightweight Builder utilizing keyword chaining and copy-on-write semantics."""

    def __init__(self, base_url: str) -> None:
        self._params: dict[str, Any] = {"url": base_url, "method": "GET", "headers": {}}

    def method(self, m: str) -> Self:
        self._params["method"] = m.upper()
        return self

    def header(self, k: str, v: str) -> Self:
        self._params["headers"][k] = v
        return self

    def build(self) -> dict[str, Any]:
        return dict(self._params)


# ==============================================================================
# 4. Driver / Demonstration
# ==============================================================================
if __name__ == "__main__":
    builder = ConcreteHttpRequestBuilder()
    director = RequestDirector(builder)

    print("=== Standard Recipe from Director ===")
    get_req = director.construct_json_get("https://api.github.com/zen")
    print(f"Constructed: {get_req.method} {get_req.url} (Headers: {get_req.headers})")

    post_req = director.construct_json_post(
        "https://api.github.com/repos", {"name": "design_patterns"}
    )
    print(f"Constructed: {post_req.method} {post_req.url} (Body: {post_req.body!r})")

    print("\n=== Custom Fluent Construction ===")
    custom_req = (
        builder.set_url("https://auth.company.com/oauth/token")
        .set_method("POST")
        .add_header("Authorization", "Bearer secret-token")
        .set_timeout(10.0)
        .set_max_retries(5)
        .build()
    )
    print(f"Custom: {custom_req.method} {custom_req.url} (Timeout: {custom_req.timeout}s)")
